name: 'Linux Unit Tests'
description: 'Runs Linux unit tests with dependencies and artifact download.'

inputs:
  artifacts-name:
    description: 'Name of the Linux build artifacts to download'
    required: true
  shell:
    description: 'Name of the Linux build artifacts to download'
    required: false
    default: 'bash'
  cmd:
    description: 'Name of the Linux build artifacts to download'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: 'Setup:  Install dependencies'
      if: inputs.shell == 'bash'
      shell: bash
      run: | 
        sudo apt-get update
        sudo apt-get -y install nasm valgrind

    - name: 'Setup:  Install dependencies'
      if: inputs.shell == 'pwsh'
      shell: pwsh
      run: echo "No dependencies to install for PowerShell"

    - name: download build artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: "${{ inputs.artifacts-name }}"
