# This is used by the action https://github.com/dorny/paths-filter
base_build: &base_build
  - 'Source/**'
  - 'tests/**'
  - 'third_party/**'
  - 'Build/**'
  - .github/workflows/base_build.yaml

ffmpeg_plugin_build: &ffmpeg_plugin_build
  - 'ffmpeg-plugin/**'
  - '.github/scripts/build_ffmpeg_plugin*'
  - 'Source/API/**'
