name: Base Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 120
    steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: 'Checkout repository'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: 'Install dependencies'
      working-directory: Build/linux
      run: sudo ./configure.sh linux 

    - name: 'Build and install'
      working-directory: Build/linux
      run: ./build.sh

  windows:
    runs-on: 'windows-2022'
    timeout-minutes: 120
    env: 
      YASM_PATH: C:\Yasm
    steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: 'Checkout repository'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: 'Install dependencies'
      working-directory: Build/windows
      shell: pwsh
      run: .\configure.ps1

    - name: 'Build'
      working-directory: Build/windows
      shell: cmd
      run: |

        call .\build.bat 2022 release
        set PATH=%YASM_PATH%;%PATH%
        C:/Yasm/yasm.exe -o "ASM_SSE2.obj" -fwin64 -I"D:\a\SVT-JPEG-XS\SVT-JPEG-XS\Source\Lib\Common\ASM_SSE2\\" -D"WIN64" -D"WIN32" -D"_WINDOWS" -D"NDEBUG" -D"ARCH_X86_64=1" -D"CMAKE_INTDIR="Release""  "D:\a\SVT-JPEG-XS\SVT-JPEG-XS\Source\Lib\Encoder\ASM_SSE2\ASM_SSE2.asm""
