name: Coverity Build

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run scans on'
        default: 'main'
        type: string

env:
  DEBIAN_FRONTEND: noninteractive

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  coverity:
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 90
    steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: 'Checkout repository'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: ${{ inputs.branch }}

    - name: 'Install dependencies'
      working-directory: Build/linux
      run: | 
           sudo apt-get update
           sudo apt-get -y install nasm

    - name: 'Run coverity'
      uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
      with:
        project: 'SVT-JPEG-XS'
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        build_language: 'cxx'
        build_platform: 'linux64'
        working-directory: '${{ github.workspace }}Build/linux'
        command: '${{ github.workspace }}Build/linux/build.sh --release'

    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: coverity-reports
        path: '${{ github.workspace }}/cov-int'