name: ffmpeg Plugin Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
env:
  LINUX_ARTIFACTS_6_1: linux-ffmpeg-6-1-build-${{ github.run_number }}
  LINUX_ARTIFACTS_7_0: linux-ffmpeg-7-0-build-${{ github.run_number }}
  WINDOWS_ARTIFACTS_6_1: linux-ffmpeg-6-1-build-${{ github.run_number }}
  WINDOWS_ARTIFACTS_7_0: linux-ffmpeg-7-0-build-${{ github.run_number }}
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.ffmpeg_plugin_build == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v2
        id: filter
        with:
          filters: .github/config/path_filters.yml

  ffmpeg-6-1-linux-build:
      needs: changes
      if: ${{ needs.changes.outputs.changed == 'true' }}
      runs-on: 'ubuntu-22.04'
      timeout-minutes: 120
      steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - name: 'Setup:  Install dependencies'
        run: | 
            sudo apt-get update
            sudo apt-get -y install nasm

      - name: 'Checkout repository'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: 'install ffmpeg plugin'
        run: .github/scripts/build_ffmpeg_plugin.sh 6.1 n

      - name: "Archive: upload artifacts"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: "${{ env.LINUX_ARTIFACTS_6_1 }}"
          retention-days: 30
          path: |
            install-dir/bin/

  ffmpeg-7-0-linux-build:
      needs: changes
      if: ${{ needs.changes.outputs.changed == 'true' }}
      runs-on: 'ubuntu-22.04'
      timeout-minutes: 120
      steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: 'Setup:  Install dependencies'
        run: | 
            sudo apt-get update
            sudo apt-get -y install nasm

      - name: 'Checkout repository'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: 'install ffmpeg plugin'
        run: .github/scripts/build_ffmpeg_plugin.sh 7.0 n

      - name: "Archive: upload artifacts"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: "${{ env.LINUX_ARTIFACTS_7_0 }}"
          retention-days: 30
          path: |
            install-dir/bin/

  ffmpeg-6-1-windows-build:
      needs: changes
      if: ${{ needs.changes.outputs.changed == 'true' }}
      runs-on: 'windows-2022'
      timeout-minutes: 120
      steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: 'Checkout repository'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 'Install dependencies'
        working-directory: "${{ github.workspace }}"
        shell: pwsh
        run: ./.github/scripts/configure.ps1

      - name: 'install msys2 shell'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc cmake mingw-w64-ucrt-x86_64-yasm

      - name: 'install ffmpeg plugin'
        working-directory: "${{ github.workspace }}"
        shell: msys2 {0}
        run: |
           export ASM_NASM="${{ env.ASM_NASM }}"
           ./.github/scripts/build_ffmpeg_plugin_msys.sh 6.1
  
      - name: "Archive: upload artifacts"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:      
          name: "${{ env.WINDOWS_ARTIFACTS_6_1 }}"
          retention-days: 30
          path: |
            install-dir/bin/

  ffmpeg-7-0-windows-build:
      needs: changes
      if: ${{ needs.changes.outputs.changed == 'true' }}
      runs-on: 'windows-2022'
      timeout-minutes: 120
      steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: 'Checkout repository'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: 'Install dependencies'
        working-directory: "${{ github.workspace }}"
        shell: pwsh
        run: ./.github/scripts/configure.ps1

      - name: 'install msys2 shell'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc cmake mingw-w64-ucrt-x86_64-yasm
      - name: 'install ffmpeg plugin'
        working-directory: "${{ github.workspace }}"
        shell: msys2 {0}
        run: |
          export ASM_NASM="${{ env.ASM_NASM }}"
          ./.github/scripts/build_ffmpeg_plugin_msys.sh 7.0
  
      - name: "Archive: upload artifacts"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:      
          name: "${{ env.WINDOWS_ARTIFACTS_7_0 }}"
          retention-days: 30
          path: |
            install-dir/bin/
