name: Fuzzy Tests

on:
  # workflow_call:
  #   inputs:
  #     branch:
  #       description: 'Branch to build'
  #       required: false
  #       type: string
  #       default: 'main'
  #     sha:
  #       description: 'SHA to build'
  #       type: string
  #       required: false
  #       default: 'HEAD'
  #     timeout:
  #       description: 'test time [seconds] (default: 60)'
  #       type: number
  #       required: false
  #       default: 60
  # workflow_dispatch:
  #   inputs:
  #     branch:
  #       description: 'Branch to build'
  #       required: false
  #       type: string
  #       default: 'main'
  #     sha:
  #       description: 'SHA to build'
  #       type: string
  #       required: false
  #       default: 'HEAD'
  #     timeout:
  #       description: 'test time [seconds] (default: 60)'
  #       type: number
  #       required: false
  #       default: 60
    pull_request:
defaults:
  run:
    shell: bash

permissions:
  contents: read


env:
  JOBS_NUM: 100
  CPATH: "/usr/local/include/svt-jpegxs"
  LD_LIBRARY_PATH: ="${LD_LIBRARY_PATH};/usr/local/lib/"
jobs:
  fuzzy-tests:
    runs-on: ['self-hosted', 'linux', 'x64', 'valgrind']
    steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: 'Checkout repository'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: 'Setup:  Install dependencies'
      working-directory: Build/linux
      run: |
            sudo apt update
            sudo apt -y install cmake nasm clang

    - name: 'Build: Debug and Release version'
      working-directory: Build/linux
      run: |
        sudo ./build.sh --install

    - name: "Build: Fuzzing binaries"
      working-directory: tests/FuzzyTests
      run: |  
        clang -lSvtJpegxs -fsanitize=fuzzer  encoder.c -o SvtJxsEncFuzzer
        clang -lSvtJpegxs -fsanitize=fuzzer  decoder.c -o SvtJxsDecFuzzer
        sudo chmod +x SvtJxsEncFuzzer
        sudo chmod +x SvtJxsDecFuzzer
